### ISSUE TITLE
Add hints into logs

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#19]
In GitLab by @m1kola on Oct 12, 2018, 16:00

Currently are writing into log if the pattern library can't find stub data for a template tag. See [this](https://github.com/torchbox/django-pattern-library/blob/85e28899376d47e8a2151ef378458661dc53fe7f/pattern_library/monkey_utils.py#L79-82):

```python
logger.warning(
    'No stub data defined for the "%s" tag in the "%s" template',
    tag_name, current_template_name
)
```

Instead of this, we can write a hint like:

```yaml
No stub data defined for the "%(tag_name)s" tag in the "%(current_template_name)s" template.
To override the template add the following into 
your yaml file:
tags:
  %(tag_name)s:
    %(tag_arguments)s:
      raw:
        some_attribute: some data
```
