### ISSUE TITLE
Allow one level of merging between context dicts in include tags - [merged]

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#34]
In GitLab by @bcdickinson on Dec 13, 2017, 10:33

_Merges include-context-merging -> master_

Fixes some missed features in the `IncludeNode` (passing extra context using `with` and isolating context using `only`). Provides first steps towards preservation of stub context data defined by parent patterns. Motivating example is breadcrumbs in CCA:

This appears in project and info page patterns:
```django
{% include 'patterns/breadcrumb.html' with current_page=page %}
```

breadcrumb.yaml provides the data required to render the breadcrumbs...
```yaml
context:
  current_page:
    get_ancestors: ...
```

... but `page` in the project and info page YAML files then hides the `current_page` definition from breadcrumb.yaml, meaning we have to repeat the `get_ancestors` definition in the project and info pages:
```yaml
context:
  page:
    title: "Project page"
    get_ancestors: ...
```

These changes will merge values one level deep, as long as they are dicts. In the above case, this means that the `current_page` dict is updated with the `page` dict from the parent pattern data, preserving the `get_ancestors` key.
